// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtlozvislczzbokdctsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0bG96dmlzbGN6emJva2RjdHNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMTQ3NTAsImV4cCI6MjA2Mzg5MDc1MH0.1xCGMdcIyMuLfjCZ6JmzP4r3XxhBocSydbhhx5Z_U6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);